apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go-highload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-highload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-highload
  template:
    metadata:
      labels:
        app: go-highload
    spec:
      containers:
        - name: go-app
          image: go-highload-service:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_ADDR
              value: "redis-service:6379"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
